# Generated by Django 3.0.5 on 2020-04-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_pdf',
            old_name='semester',
            new_name='semesters',
        ),
    ]
