# Generated by Django 3.0.5 on 2020-04-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200425_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_pdf',
            old_name='semesters',
            new_name='semester',
        ),
    ]
