# Generated by Django 3.0.5 on 2020-04-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200426_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_pdf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/image/'),
        ),
    ]
